version: "3.7"
services:
  merchant_component_db:
    image: postgres:latest
    container_name: merchant_component_db
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_PASSWORD=merchant_component
      - POSTGRES_USER=merchant_component
      - POSTGRES_DB=merchant_component
      - PGDATA=/data/merchant_component_db
    volumes:
      - merchant_component_db:/data/merchant_component_db
    networks:
      - web
